[2024-05-01T00:33:29.167+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T00:33:29.191+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T00:33:29.191+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T00:33:29.191+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-05-01T00:33:29.192+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T00:33:29.219+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 00:00:00+00:00
[2024-05-01T00:33:29.242+0000] {standard_task_runner.py:55} INFO - Started process 455 to run task
[2024-05-01T00:33:29.245+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpyunkl7t6']
[2024-05-01T00:33:29.251+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask is_api_available
[2024-05-01T00:33:29.337+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [running]> on host 3625f7351c61
[2024-05-01T00:33:29.451+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-30T00:00:00+00:00
[2024-05-01T00:33:29.453+0000] {http.py:120} INFO - Poking: api/
[2024-05-01T00:33:29.494+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 189, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 135, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 126, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2024-05-01T00:33:29.506+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T000000, start_date=20240501T003329, end_date=20240501T003329
[2024-05-01T00:33:29.521+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task is_api_available (The conn_id `user_api` isn't defined; 455)
[2024-05-01T00:33:29.552+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-01T00:33:29.577+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T01:35:17.838+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:35:17.861+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:35:17.862+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:35:17.863+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-05-01T01:35:17.863+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:35:17.881+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 00:00:00+00:00
[2024-05-01T01:35:17.887+0000] {standard_task_runner.py:55} INFO - Started process 2118 to run task
[2024-05-01T01:35:17.890+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp5r5fhbq_']
[2024-05-01T01:35:17.892+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask is_api_available
[2024-05-01T01:35:17.956+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [running]> on host fe27111d44a9
[2024-05-01T01:35:18.022+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-30T00:00:00+00:00
[2024-05-01T01:35:18.023+0000] {http.py:120} INFO - Poking: api/
[2024-05-01T01:35:18.041+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/sensors/base.py", line 189, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 135, in poke
    raise exc
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/sensors/http.py", line 126, in poke
    extra_options=self.extra_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 128, in run
    session = self.get_conn(headers)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/hooks/http.py", line 82, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `user_api` isn't defined
[2024-05-01T01:35:18.046+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T000000, start_date=20240501T013517, end_date=20240501T013518
[2024-05-01T01:35:18.055+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task is_api_available (The conn_id `user_api` isn't defined; 2118)
[2024-05-01T01:35:18.102+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-01T01:35:18.134+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-01T01:37:53.629+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:37:53.640+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:37:53.641+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:37:53.641+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-05-01T01:37:53.641+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:37:53.657+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 00:00:00+00:00
[2024-05-01T01:37:53.665+0000] {standard_task_runner.py:55} INFO - Started process 2250 to run task
[2024-05-01T01:37:53.668+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpd48mr8id']
[2024-05-01T01:37:53.670+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask is_api_available
[2024-05-01T01:37:53.741+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [running]> on host fe27111d44a9
[2024-05-01T01:37:53.820+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-30T00:00:00+00:00
[2024-05-01T01:37:53.822+0000] {http.py:120} INFO - Poking: api/
[2024-05-01T01:37:53.832+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-05-01T01:37:53.862+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-05-01T01:37:54.688+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-05-01T01:37:54.708+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T000000, start_date=20240501T013753, end_date=20240501T013754
[2024-05-01T01:37:54.763+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-05-01T01:37:54.801+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T01:40:54.090+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:40:54.101+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T01:40:54.102+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:40:54.102+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-05-01T01:40:54.103+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-01T01:40:54.117+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-04-30 00:00:00+00:00
[2024-05-01T01:40:54.123+0000] {standard_task_runner.py:55} INFO - Started process 2409 to run task
[2024-05-01T01:40:54.126+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp25x7di4_']
[2024-05-01T01:40:54.128+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask is_api_available
[2024-05-01T01:40:54.183+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-04-30T00:00:00+00:00 [running]> on host fe27111d44a9
[2024-05-01T01:40:54.243+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-04-30T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-04-30T00:00:00+00:00
[2024-05-01T01:40:54.244+0000] {http.py:120} INFO - Poking: api/
[2024-05-01T01:40:54.253+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-05-01T01:40:54.255+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-05-01T01:40:54.814+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2024-05-01T01:40:54.823+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20240430T000000, start_date=20240501T014054, end_date=20240501T014054
[2024-05-01T01:40:54.860+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2024-05-01T01:40:54.894+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
